### ISSUE TITLE
reserved "Object" name

### ISSUE THREAD

**Issue by frostbane** [ircmaxell/filterus#15]
Hi,

I tried running the unit tests under php7.2.12 and it fails in

Filterus\Filters\Object

```
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved
```

I am planning to refactor it and submit a pull request, but before I make any changes do you have any ideas on what class name should it be changed to?

**Comment by ircmaxell** [comment]
I would say keep it aligned to the existing naming conventions for these collisions. For example [`Arrays`](https://github.com/ircmaxell/filterus/blob/master/lib/Filterus/Filters/Arrays.php), [`ints`](https://github.com/ircmaxell/filterus/blob/master/lib/Filterus/Filters/Ints.php), etc.
